### ISSUE TITLE
Activating extension `waderyan.gitblame` failed: Cannot find module '../src/textDecorator'.

### ISSUE THREAD

**Issue by lucamartini** [waderyan/vscode-gitblame#31]
Hi, 

the latest gitblame release (1st of May 2017) does not start on my visual studio code.
The console prints the following:

Activating extension `waderyan.gitblame` failed: Cannot find module '../src/textDecorator'.

This is the error stack:

[Extension Host] Here is the error stack:  Error: Cannot find module '../src/textDecorator'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/luca/.vscode/extensions/waderyan.gitblame-1.8.0/out/src/controller.js:4:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/luca/.vscode/extensions/waderyan.gitblame-1.8.0/out/src/extension.js:5:22)
    at Module._compile (module.js:556:32)

**Comment by Sertion** [comment]
The issue is being discussed [here](https://github.com/Sertion/vscode-gitblame/issues/9).

**Comment by lucamartini** [comment]
Ah thanks!, I'm closing this then.
